# https://taskfile.dev

$schema: https://taskfile.dev/schema.json
version: '3'

tasks:
  run:
    vars:
      CMD_DIRS:
        sh: |
          find cmd -mindepth 1 -maxdepth 1 -type d | sort
    desc: Run all days and parts
    cmds:
      - for:
          var: CMD_DIRS
        cmd: go run ./{{ .ITEM }}/...